# Generated by Django 3.0.7 on 2020-07-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_auto_20200713_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='school',
            old_name='person_incharge',
            new_name='school_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='scool_auth',
        ),
        migrations.AddField(
            model_name='school',
            name='incharge_contact_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='incharge_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='incharge_name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.DeleteModel(
            name='AuthorityType',
        ),
        migrations.AddField(
            model_name='school',
            name='school_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.AffiliationType'),
        ),
    ]
