# Generated by Django 3.0.7 on 2020-07-20 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_admin', '0006_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='incharge_contact_no',
        ),
        migrations.CreateModel(
            name='IndividualStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('standard', models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10)),
                ('password', models.CharField(max_length=40)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
