# Generated by Django 3.0.7 on 2020-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0007_auto_20200720_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualstudents',
            name='standard',
        ),
        migrations.AddField(
            model_name='individualstudents',
            name='course_pursuing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualstudents',
            name='current_institution_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
