# Generated by Django 3.0.7 on 2020-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0008_auto_20200720_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualstudents',
            name='assessment_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='assessment_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assessment_given',
            field=models.IntegerField(default=0),
        ),
    ]
