# Generated by Django 3.0.7 on 2020-07-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0009_auto_20200720_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.Teacher'),
        ),
    ]
