# Generated by Django 3.0.7 on 2020-07-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_questioncategory_updated_by'),
        ('project_admin', '0010_student_teacher_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAssignedTestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.School')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.Student')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Test')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.IndividualStudents')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Test')),
            ],
        ),
    ]
