# Generated by Django 3.0.7 on 2020-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0011_individualtestpaper_schoolassignedtestpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualstudents',
            name='student_type',
            field=models.CharField(choices=[('ATL', 'ATL'), ('Non ATL', 'Non ATL')], default='ATL', max_length=30),
        ),
    ]
