# Generated by Django 3.0.7 on 2020-07-21 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_admin', '0012_individualstudents_student_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=100)),
                ('government', models.CharField(max_length=50)),
                ('authority_type', models.CharField(choices=[('CBSE Authority', 'CBSE Authority'), ('Niti Aayog', 'Niti Aayog'), ('State Eductaion', 'State Eductaion'), ('Cooperation', 'Cooperation')], max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
