# Generated by Django 3.0.7 on 2020-07-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_questioncategory_updated_by'),
        ('project_admin', '0014_authorityaccount_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('School Student', 'School Student'), ('e-learning Student', 'e-learning Student')], max_length=30)),
                ('stu_class', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
                ('test_datetime', models.DateTimeField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.Student')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.School')),
                ('test_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Test')),
            ],
        ),
    ]
