# Generated by Django 3.0.7 on 2020-07-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0015_assigntest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntest',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.School'),
        ),
        migrations.AlterField(
            model_name='assigntest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.Student'),
        ),
    ]
