# Generated by Django 3.0.7 on 2020-07-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0017_assigntest_test_appeared'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntest',
            name='elearning_stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.IndividualStudents'),
        ),
        migrations.AlterField(
            model_name='assigntest',
            name='stu_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
