# Generated by Django 3.0.7 on 2020-07-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0018_auto_20200722_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntest',
            name='test_status',
            field=models.CharField(default='pending', max_length=60),
        ),
    ]
