# Generated by Django 3.0.7 on 2020-07-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(default='')),
                ('question_tags', models.CharField(choices=[('Single Correct', 'Single'), ('Multiple Correct', 'Multiple'), ('Passage Based', 'Passage')], default='Single', max_length=60)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], default='Easy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Language')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('question_to_deliver', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('test_duration', models.PositiveIntegerField()),
                ('test_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='TestLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_lang', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Test')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='lang_wise_q',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='language',
        ),
        migrations.DeleteModel(
            name='LanuguageQuestions',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Test'),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question'),
        ),
    ]
