# Generated by Django 3.0.7 on 2020-07-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20200707_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='package',
            field=models.CharField(default='p1', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject_name',
            field=models.CharField(default='Embedded', max_length=90),
        ),
    ]
