# Generated by Django 3.1 on 2020-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_options_ans_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='ans_point',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
